# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adfd87d5e3994cc9f2a9a37a3b3d08ef"
name = "Poptify Demo"
application_url = "https://poptify.chuot.io.vn"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,read_metaobjects,write_metaobjects,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[shop.metafields.app.settings]
name = "Poptify settings"
type = "json"

[shop.metafields.app.popups]
name = "Poptify popups"
type = "json"

[shop.metafields.app.bars]
name = "Poptify announcement bars"
type = "json"

[shop.metafields.app.sliders]
name = "Poptify product sliders"
type = "json"

[auth]
redirect_urls = [ "https://poptify.chuot.io.vn/auth/callback" ]

[webhooks]
api_version = "2025-10"
